version: "3.7"

services:
  price-calculator-client:
    image: pricecalculator/client
    build: client
    ports:
      - "5000:80"
    restart: "unless-stopped"

  price-calculator-server:
    image: pricecalculator/server
    build: server
    ports:
      - "9096:9096"
    restart: "unless-stopped"
